import Foundation
#if canImport(UIKit)
import UIKit
import CoreText
#endif

// MARK: - PDFExportError

public enum PDFExportError: Error, LocalizedError, Sendable {
    case noContent
    case renderingFailed(String)

    public var errorDescription: String? {
        switch self {
        case .noContent:
            return "No content available to export."
        case .renderingFailed(let reason):
            return "PDF rendering failed: \(reason)"
        }
    }
}

// MARK: - PDFExportServiceProtocol

/// Protocol for exporting document analyses as PDF data.
public protocol PDFExportServiceProtocol: Sendable {
    /// Generates PDF data for a document and its analysis result.
    func exportAnalysis(document: Document, result: AnalysisResult) throws -> Data

    /// Generates PDF data for a comparison result.
    func exportComparison(_ comparison: ComparisonResult) throws -> Data

    /// Generates a plain-text report suitable for sharing.
    func generateTextReport(document: Document, result: AnalysisResult) -> String
}

// MARK: - PDFExportService

public final class PDFExportService: PDFExportServiceProtocol, Sendable {

    public init() {}

    public func exportAnalysis(document: Document, result: AnalysisResult) throws -> Data {
        let text = generateTextReport(document: document, result: result)
        guard !text.isEmpty else {
            throw PDFExportError.noContent
        }
        return renderTextToPDF(text)
    }

    public func exportComparison(_ comparison: ComparisonResult) throws -> Data {
        let text = generateComparisonTextReport(comparison)
        guard !text.isEmpty else {
            throw PDFExportError.noContent
        }
        return renderTextToPDF(text)
    }

    public func generateTextReport(document: Document, result: AnalysisResult) -> String {
        var lines: [String] = []

        lines.append("PRIVLENS ANALYSIS REPORT")
        lines.append(String(repeating: "=", count: 40))
        lines.append("")
        lines.append("Document: \(document.title)")
        lines.append("Type: \(result.documentType.displayName)")
        lines.append("Scanned: \(formattedDate(document.dateScanned))")
        lines.append("Pages: \(document.pageCount)")
        lines.append("")

        // Summary
        lines.append("SUMMARY")
        lines.append(String(repeating: "-", count: 40))
        lines.append(result.summary)
        lines.append("")

        // Red Flags
        if !result.redFlags.isEmpty {
            lines.append("RED FLAGS (\(result.redFlags.count))")
            lines.append(String(repeating: "-", count: 40))
            for (index, flag) in result.redFlags.enumerated() {
                lines.append("  \(index + 1). \(flag)")
            }
            lines.append("")
        }

        // Key Insights
        if !result.keyInsights.isEmpty {
            lines.append("KEY INSIGHTS (\(result.keyInsights.count))")
            lines.append(String(repeating: "-", count: 40))
            for (index, insight) in result.keyInsights.enumerated() {
                lines.append("  \(index + 1). \(insight)")
            }
            lines.append("")
        }

        // Action Items
        if !result.actionItems.isEmpty {
            lines.append("ACTION ITEMS (\(result.actionItems.count))")
            lines.append(String(repeating: "-", count: 40))
            for (index, item) in result.actionItems.enumerated() {
                lines.append("  \(index + 1). \(item)")
            }
            lines.append("")
        }

        lines.append(String(repeating: "=", count: 40))
        lines.append("Generated by Privlens - 100% on-device, 100% private.")
        lines.append("This report was generated from AI analysis and should not be considered legal or financial advice.")

        return lines.joined(separator: "\n")
    }

    // MARK: - Comparison Report

    private func generateComparisonTextReport(_ comparison: ComparisonResult) -> String {
        var lines: [String] = []

        lines.append("PRIVLENS COMPARISON REPORT")
        lines.append(String(repeating: "=", count: 40))
        lines.append("")
        lines.append("Document A: \(comparison.documentATitle)")
        lines.append("Document B: \(comparison.documentBTitle)")
        lines.append("Compared: \(formattedDate(comparison.comparedAt))")
        lines.append("Similarity: \(Int(comparison.similarityScore * 100))%")
        lines.append("")

        // Summary
        lines.append("SUMMARY")
        lines.append(String(repeating: "-", count: 40))
        lines.append(comparison.summary)
        lines.append("")

        // Differences
        if !comparison.differences.isEmpty {
            lines.append("DIFFERENCES (\(comparison.differences.count))")
            lines.append(String(repeating: "-", count: 40))

            let critical = comparison.differences.filter { $0.severity >= 0.7 }
            let other = comparison.differences.filter { $0.severity < 0.7 }

            if !critical.isEmpty {
                lines.append("")
                lines.append("  Critical:")
                for diff in critical {
                    lines.append("    - \(diff.label)")
                    lines.append("      Doc A: \(diff.documentAValue)")
                    lines.append("      Doc B: \(diff.documentBValue)")
                }
            }

            if !other.isEmpty {
                lines.append("")
                lines.append("  Other:")
                for diff in other {
                    lines.append("    - \(diff.label)")
                    lines.append("      Doc A: \(diff.documentAValue)")
                    lines.append("      Doc B: \(diff.documentBValue)")
                }
            }
            lines.append("")
        }

        lines.append(String(repeating: "=", count: 40))
        lines.append("Generated by Privlens - 100% on-device, 100% private.")

        return lines.joined(separator: "\n")
    }

    // MARK: - PDF Rendering

    private func renderTextToPDF(_ text: String) -> Data {
        #if canImport(UIKit)
        return renderTextToPDFWithUIKit(text)
        #else
        // On non-UIKit platforms, return the text as UTF-8 data (plain text fallback).
        return Data(text.utf8)
        #endif
    }

    #if canImport(UIKit)
    private func renderTextToPDFWithUIKit(_ text: String) -> Data {
        let pageWidth: CGFloat = 612.0  // US Letter
        let pageHeight: CGFloat = 792.0
        let margin: CGFloat = 50.0

        let textRect = CGRect(
            x: margin,
            y: margin,
            width: pageWidth - margin * 2,
            height: pageHeight - margin * 2
        )

        let pdfData = NSMutableData()
        UIGraphicsBeginPDFContextToData(pdfData, CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight), nil)

        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.lineBreakMode = .byWordWrapping

        let attrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 11),
            .paragraphStyle: paragraphStyle,
        ]

        let attributedString = NSAttributedString(string: text, attributes: attrs)
        let framesetter = CTFramesetterCreateWithAttributedString(attributedString)
        var currentIndex = 0
        let textLength = attributedString.length

        while currentIndex < textLength {
            UIGraphicsBeginPDFPage()
            let path = CGPath(rect: textRect, transform: nil)
            let range = CFRangeMake(currentIndex, 0)
            let frame = CTFramesetterCreateFrame(framesetter, range, path, nil)

            if let context = UIGraphicsGetCurrentContext() {
                context.translateBy(x: 0, y: pageHeight)
                context.scaleBy(x: 1.0, y: -1.0)
                CTFrameDraw(frame, context)
            }

            let visibleRange = CTFrameGetVisibleStringRange(frame)
            currentIndex += max(visibleRange.length, 1)
        }

        UIGraphicsEndPDFContext()
        return pdfData as Data
    }
    #endif

    // MARK: - Helpers

    private func formattedDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        formatter.locale = Locale(identifier: "en_US")
        return formatter.string(from: date)
    }
}
